apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: remote-write-proxy
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: prometheus-ams
  name: prometheus-remote-write-proxy-config
data:
  nginx.conf: |
    daemon off;
    worker_processes 1;
    error_log /dev/stderr;
    pid /tmp/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      server {
        listen *:8080;
        server_name _;
        access_log  /dev/stdout  main;
        error_log /dev/stderr;

        location / {
          proxy_set_header THANOS-TENANT FB870BF3-9F3A-44FF-9BF7-D7A047A52F43;
          proxy_pass http://observatorium-thanos-receive.telemeter-production.svc.cluster.local:19291;
        }
      }
    }
