---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: observatorium-metrics-production
spec:
  groups:
  - name: observatorium-metrics
    rules:
    - alert: ObservatoriumNoStoreBlocksLoaded
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/no-dashboard/observatorium-metrics?orgId=1&refresh=10s&var-datasource={{$externalLabels.cluster}}-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
        description: Observatorium Thanos Store {{$labels.namespace}}/{{$labels.job}} has not loaded any blocks in the last 6 hours.
        message: Observatorium Thanos Store {{$labels.namespace}}/{{$labels.job}} has not loaded any blocks in the last 6 hours.
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#observatoriumnostoreblocksloaded
        summary: Observatorium Thanos Store has not loaded any blocks in the last 6 hours.
      expr: |
        absent(thanos_bucket_store_blocks_last_loaded_timestamp_seconds) != 1 and (time() - thanos_bucket_store_blocks_last_loaded_timestamp_seconds) > 6 * 60 * 60
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - alert: ObservatoriumNoRulesLoaded
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/no-dashboard/observatorium-metrics?orgId=1&refresh=10s&var-datasource={{$externalLabels.cluster}}-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
        description: Observatorium Thanos Ruler {{$labels.namespace}}/{{$labels.job}} has not any rules loaded.
        message: Observatorium Thanos Ruler {{$labels.namespace}}/{{$labels.job}} has not any rules loaded.
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#observatoriumnorulesloaded
        summary: Observatorium Thanos Ruler has not any rule to evaluate. This should not have happened. Check out the configuration.
      expr: |
        sum by (namespace, job) (thanos_rule_loaded_rules{job=~"observatorium-thanos-rule.*|observatorium-thanos-stateless-rule.*|observatorium-thanos-metric-federation-rule.*|observatorium-thanos-metric-fed-stateless-rule.*"}) == 0
      for: 5m
      labels:
        service: telemeter
        severity: critical
    - alert: ObservatoriumPersistentVolumeUsageHigh
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/no-dashboard/observatorium-metrics?orgId=1&refresh=10s&var-datasource={{$externalLabels.cluster}}-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
        description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} has {{ printf "%0.2f" $value }}% of free space
        message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} has {{ printf "%0.2f" $value }}% of free space
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#observatoriumpersistentvolumeusagehigh
        summary: One or more of the PersistentVolumes in Observatorium is over 90% full. They might need to be extended.
      expr: |
        100 * kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"^openshift-.*$",persistentvolumeclaim=~"data-observatorium-thanos-.*"}
        /
        kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"^openshift-.*$",persistentvolumeclaim=~"data-observatorium-thanos-.*"} < 10
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - alert: ObservatoriumPersistentVolumeUsageCritical
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/no-dashboard/observatorium-metrics?orgId=1&refresh=10s&var-datasource={{$externalLabels.cluster}}-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
        description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is only {{ printf "%0.2f" $value }}% free
        message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is only {{ printf "%0.2f" $value }}% free
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#observatoriumpersistentvolumeusagecritical
        summary: One or more of the PersistentVolumes in Observatorium is critically filled. They need to be extended.
      expr: |
        100 * kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"^openshift-.*$",persistentvolumeclaim=~"data-observatorium-thanos-.*"}
        /
        kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"^openshift-.*$",persistentvolumeclaim=~"data-observatorium-thanos-.*"} < 5
      for: 10m
      labels:
        service: telemeter
        severity: critical
