---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: telemeter-slos-stage
spec:
  groups:
  - name: telemeter-upload.slo.rules
    rules:
    - alert: TelemeterUploadErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /upload is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeteruploaderrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate5m{route="telemeter-server-upload"}) > (14.40 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate1h{route="telemeter-server-upload"}) > (14.40 * (1-0.98000))
      for: 2m
      labels:
        route: telemeter-server-upload
        service: telemeter
        severity: high
    - alert: TelemeterUploadErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /upload is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeteruploaderrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate30m{route="telemeter-server-upload"}) > (6.00 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate6h{route="telemeter-server-upload"}) > (6.00 * (1-0.98000))
      for: 15m
      labels:
        route: telemeter-server-upload
        service: telemeter
        severity: high
    - alert: TelemeterUploadErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /upload is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeteruploaderrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate2h{route="telemeter-server-upload"}) > (3.00 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate1d{route="telemeter-server-upload"}) > (3.00 * (1-0.98000))
      for: 1h
      labels:
        route: telemeter-server-upload
        service: telemeter
        severity: medium
    - alert: TelemeterUploadErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /upload is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeteruploaderrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate6h{route="telemeter-server-upload"}) > (1.00 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate3d{route="telemeter-server-upload"}) > (1.00 * (1-0.98000))
      for: 3h
      labels:
        route: telemeter-server-upload
        service: telemeter
        severity: medium
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[1d]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[1d]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate1d
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[1h]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[1h]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate1h
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[2h]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[2h]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate2h
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[30m]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[30m]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate30m
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[3d]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[3d]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate3d
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[5m]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[5m]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate5m
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload",code="5xx"}[6h]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-upload"}[6h]))
      labels:
        route: telemeter-server-upload
      record: haproxy_server_http_responses_total:burnrate6h
  - name: telemeter-authorize.slo.rules
    rules:
    - alert: TelemeterAuthorizeErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /authorize is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeterauthorizeerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate5m{route="telemeter-server-authorize"}) > (14.40 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate1h{route="telemeter-server-authorize"}) > (14.40 * (1-0.98000))
      for: 2m
      labels:
        route: telemeter-server-authorize
        service: telemeter
        severity: high
    - alert: TelemeterAuthorizeErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /authorize is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeterauthorizeerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate30m{route="telemeter-server-authorize"}) > (6.00 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate6h{route="telemeter-server-authorize"}) > (6.00 * (1-0.98000))
      for: 15m
      labels:
        route: telemeter-server-authorize
        service: telemeter
        severity: high
    - alert: TelemeterAuthorizeErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /authorize is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeterauthorizeerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate2h{route="telemeter-server-authorize"}) > (3.00 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate1d{route="telemeter-server-authorize"}) > (3.00 * (1-0.98000))
      for: 1h
      labels:
        route: telemeter-server-authorize
        service: telemeter
        severity: medium
    - alert: TelemeterAuthorizeErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter /authorize is burning too much error budget to gurantee overall availability
        runbook: https://gitlab.cee.redhat.com/observatorium/configuration/blob/master/docs/sop/telemeter.md#telemeterauthorizeerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate6h{route="telemeter-server-authorize"}) > (1.00 * (1-0.98000))
        and
        sum(haproxy_server_http_responses_total:burnrate3d{route="telemeter-server-authorize"}) > (1.00 * (1-0.98000))
      for: 3h
      labels:
        route: telemeter-server-authorize
        service: telemeter
        severity: medium
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[1d]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[1d]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate1d
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[1h]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[1h]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate1h
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[2h]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[2h]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate2h
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[30m]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[30m]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate30m
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[3d]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[3d]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate3d
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[5m]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[5m]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate5m
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize",code="5xx"}[6h]))
        /
        sum(rate(haproxy_server_http_responses_total{route="telemeter-server-authorize"}[6h]))
      labels:
        route: telemeter-server-authorize
      record: haproxy_server_http_responses_total:burnrate6h
