apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/283e7002d85c08126681241df2fdb22b/mst-production-slos?orgId=1&refresh=10s&var-datasource=telemeter-prod-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API /rules endpoint is burning too much error budget to guarantee
      availability SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APIRulesReadAvailabilityErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: mst-production
    pyrra.dev/service: observatorium-api
  name: api-rules-read-availability-slo
spec:
  alerting:
    name: APIRulesReadAvailabilityErrorBudgetBurning
  description: API /rules endpoint is burning too much error budget to guarantee availability
    SLOs.
  indicator:
    ratio:
      errors:
        metric: http_requests_total{job="observatorium-observatorium-mst-api", handler="rules",
          method="GET", group="metricsv1", code=~"^5..$"}
      grouping: null
      total:
        metric: http_requests_total{job="observatorium-observatorium-mst-api", handler="rules",
          method="GET", group="metricsv1", code!~"^4..$"}
  target: "99.5"
  window: 28d
status: {}
