apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/283e7002d85c08126681241df2fdb22b/mst-production-slos?orgId=1&refresh=10s&var-datasource=telemeter-prod-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API /query endpoint for rules evaluation is burning too much
      error budget for 100M samples, to guarantee latency SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APIMetricsRulenReadLatency100MErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: mst-production
    pyrra.dev/service: observatorium-api
  name: api-metrics-rule-read-100M-latency-slo
spec:
  alerting:
    name: APIMetricsRulenReadLatency100MErrorBudgetBurning
  description: API /query endpoint for rules evaluation is burning too much error
    budget for 100M samples, to guarantee latency SLOs.
  indicator:
    latency:
      grouping: null
      success:
        metric: up_custom_query_duration_seconds_bucket{query="rule-query-path-sli-1M-samples",
          namespace="observatorium-mst-production", http_code=~"^2..$", le="120"}
      total:
        metric: up_custom_query_duration_seconds_count{query="rule-query-path-sli-1M-samples",
          namespace="observatorium-mst-production", http_code=~"^2..$"}
  target: "90"
  window: 28d
status: {}
