apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/92520ea4d6976f30d1618164e186ef9b/mst-stage-slos?orgId=1&refresh=10s&var-datasource=app-sre-stage-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API logs /tail is burning too much error budget to guarantee
      availability SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APILogsTailAvailabilityErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: mst-stage
    service: observatorium-api
  name: api-logs-tail-availability-slo
spec:
  alerting:
    name: APILogsTailAvailabilityErrorBudgetBurning
  description: API logs /tail is burning too much error budget to guarantee availability
    SLOs.
  indicator:
    ratio:
      errors:
        metric: http_requests_total{job="observatorium-observatorium-mst-api", handler="tail",
          group="logsv1", code=~"^5..$"}
      grouping: null
      total:
        metric: http_requests_total{job="observatorium-observatorium-mst-api", handler="tail",
          group="logsv1", code!~"^4..$"}
  target: "99"
  window: 28d
status: {}
