apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/7f4df1c2d5518d5c3f2876ca9bb874a8/rhobsp02ue1-production-slos?orgId=1&refresh=10s&var-datasource=rhobsp02ue1-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API /rules/raw endpoint for reads is burning too much error
      budget to guarantee availability SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APIRulesRawReadAvailabilityErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: rhobsp02ue1-production
    service: observatorium-api
  name: api-rules-raw-read-availability-slo
spec:
  alerting:
    name: APIRulesRawReadAvailabilityErrorBudgetBurning
  description: API /rules/raw endpoint for reads is burning too much error budget
    to guarantee availability SLOs.
  indicator:
    ratio:
      errors:
        metric: http_requests_total{job="observatorium-observatorium-mst-api", handler="rules-raw",
          method="GET", group="metricsv1", code=~"^5..$"}
      grouping: null
      total:
        metric: http_requests_total{job="observatorium-observatorium-mst-api", handler="rules-raw",
          method="GET", group="metricsv1", code!~"^4..$"}
  target: "99.5"
  window: 28d
status: {}
