apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/7f4df1c2d5518d5c3f2876ca9bb874a8/rhobsp02ue1-production-slos?orgId=1&refresh=10s&var-datasource=rhobsp02ue1-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API /query endpoint is burning too much error budget for 1M
      samples, to guarantee latency SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APIMetricsReadLatency1MErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: rhobsp02ue1-production
    pyrra.dev/service: observatorium-thanos-query
  name: api-metrics-read-1M-latency-slo
spec:
  alerting:
    name: APIMetricsReadLatency1MErrorBudgetBurning
  description: API /query endpoint is burning too much error budget for 1M samples,
    to guarantee latency SLOs.
  indicator:
    latency:
      grouping: null
      success:
        metric: up_custom_query_duration_seconds_bucket{query="query-path-sli-1M-samples",
          namespace="observatorium-mst-production", code=~"^2..$", le="10"}
      total:
        metric: up_custom_query_duration_seconds_count{query="query-path-sli-1M-samples",
          namespace="observatorium-mst-production", code=~"^2..$"}
  target: "90"
  window: 28d
status: {}
