apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/f9fa7677fb4a2669f123f9a0f2234b47/telemeter-production-slos?orgId=1&refresh=10s&var-datasource=telemeter-prod-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API /query endpoint is burning too much error budget for 100M
      samples, to guarantee latency SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APIMetricsReadLatency10MErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: telemeter-production
    pyrra.dev/service: observatorium-thanos-query
  name: api-metrics-read-10M-latency-slo
spec:
  alerting:
    name: APIMetricsReadLatency10MErrorBudgetBurning
  description: API /query endpoint is burning too much error budget for 100M samples,
    to guarantee latency SLOs.
  indicator:
    latency:
      grouping: null
      success:
        metric: up_custom_query_duration_seconds_bucket{query="query-path-sli-10M-samples",
          namespace="observatorium-production", code=~"^2..$", le="30"}
      total:
        metric: up_custom_query_duration_seconds_count{query="query-path-sli-10M-samples",
          namespace="observatorium-production", code=~"^2..$"}
  target: "90"
  window: 28d
status: {}
