apiVersion: v1
kind: ConfigMap
metadata:
  name: observatorium-tenants
  labels:
    app.kubernetes.io/name: thanos-receive-controller
data:
  hashrings.json: |-
    [
      {
        "hashring": "default",
        "tenants": []
      }
    ]
